//! Code generation for batch operations (QueryExt trait + implementations)
//!
//! Generates the complete batch operations infrastructure:
//! - QueryExt trait definition
//! - Query builder structs (InsertManyQuery, UpdateColsQuery)
//! - QueryExt implementations for each table struct

use crate::config::Config;
use crate::schema_introspection::TableSchema;
use heck::{ToSnakeCase, ToUpperCamelCase};
use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use std::collections::HashMap;

/// Generate the complete batch operations module
///
/// This includes:
/// 1. QueryExt trait definition
/// 2. Query builder structs and implementations
/// 3. QueryExt implementations for all table structs
pub fn gen_batch_ops_module(tables: &[TableSchema], config: &Config) -> TokenStream {
    if tables.is_empty() {
        return quote! {};
    }

    // Build type mappings from config
    let type_mappings: HashMap<String, String> = config
        .types
        .mapping
        .iter()
        .map(|(k, v)| {
            let rust_type = match v {
                crate::config::TypeMapping::Simple(s) => s.clone(),
                crate::config::TypeMapping::Detailed { rust_type, .. } => rust_type.clone(),
            };
            (k.clone(), rust_type)
        })
        .collect();

    let trait_def = gen_query_ext_trait();
    let builders = gen_query_builders();
    let col_enums: Vec<TokenStream> = tables
        .iter()
        .map(|table| gen_column_enum(table, config))
        .collect();
    let impls: Vec<TokenStream> = tables
        .iter()
        .map(|table| gen_query_ext_impl(table, &type_mappings, config))
        .collect();

    let slice_ext = gen_slice_ext_trait();

    quote! {
        //! Auto-generated batch operations infrastructure
        //! DO NOT EDIT - Regenerated by Clorinde
        //!
        //! This module provides:
        //! - QueryExt trait for batch database operations
        //! - Query builders (InsertManyQuery, UpdateColsQuery)
        //! - QueryExt implementations for all table structs

        use tokio_postgres::{Row, types::ToSql, Error};
        use crate::client::async_::GenericClient;
        use crate::tables::*;

        #(#col_enums)*

        /// Column name constants and batch operation infrastructure
        ///
        /// This module is intentionally named `__private` to discourage direct use.
        /// Users should access it through the public trait methods instead.
        pub mod __private {
            use super::*;

            #trait_def

            #slice_ext

            #builders

            #(#impls)*
        }

        // Re-export the traits for easy access
        pub use __private::{QueryExt, BatchInsertExt};
    }
}

/// Generate the QueryExt trait definition
fn gen_query_ext_trait() -> TokenStream {
    quote! {
        /// Trait for database table structs to enable batch operations
        ///
        /// Generic parameter N is the number of columns in the table.
        pub trait QueryExt<const N: usize>: Sized + Sync {
            /// SQL table name (e.g., "public.restaurants")
            const TABLE_NAME: &'static str;

            /// All column names in ordinal order
            const COLS: [&'static str; N];

            /// Convert struct fields to SQL parameters
            fn to_params(&self) -> [&(dyn ToSql + Sync); N];

            /// Construct struct from database row
            fn from_row(row: Row) -> Self;

            /// Start building a batch INSERT statement
            ///
            /// # Example
            /// ```rust
            /// use restaurants_col::*;
            ///
            /// let rows = vec![restaurant1, restaurant2];
            ///
            /// // Insert with auto-generated columns excluded
            /// RestaurantsRow::insert_many(&rows)
            ///     .excluding_cols(&[ID, CREATED_AT_MS, UPDATED_AT_MS])
            ///     .exec(&client)
            ///     .await?;
            ///
            /// // Upsert on conflict
            /// RestaurantsRow::insert_many(&rows)
            ///     .excluding_cols(&[ID, CREATED_AT_MS])
            ///     .on_conflict_do_update(
            ///         &[GOOGLE_ID],  // conflict columns
            ///         &[DISPLAY_NAME, RATING],  // columns to update
            ///     )
            ///     .query(&client)  // Returns inserted/updated rows
            ///     .await?;
            /// ```
            fn insert_many(rows: &[Self]) -> InsertManyQuery<'_, Self, N> {
                InsertManyQuery::new(rows)
            }

            /// Start building an UPDATE statement
            ///
            /// # Example
            /// ```rust
            /// use restaurants_col::*;
            ///
            /// restaurant
            ///     .update_cols(&[RATING, USER_RATING_COUNT])
            ///     .where_cols(&[GOOGLE_ID])
            ///     .exec(&client)
            ///     .await?;
            /// ```
            fn update_cols<'a>(&'a self, cols: &'a [&'a str]) -> UpdateColsQuery<'a, Self, N> {
                UpdateColsQuery::new(self, cols)
            }
        }
    }
}

/// Generate extension trait for Vec/slices
fn gen_slice_ext_trait() -> TokenStream {
    quote! {
        /// Extension trait to enable calling .insert_many() on Vec<T> and &[T]
        pub trait BatchInsertExt<T: QueryExt<N>, const N: usize> {
            fn insert_many(&self) -> InsertManyQuery<'_, T, N>;
        }

        impl<T: QueryExt<N>, const N: usize> BatchInsertExt<T, N> for Vec<T> {
            fn insert_many(&self) -> InsertManyQuery<'_, T, N> {
                InsertManyQuery::new(self.as_slice())
            }
        }

        impl<T: QueryExt<N>, const N: usize> BatchInsertExt<T, N> for &[T] {
            fn insert_many(&self) -> InsertManyQuery<'_, T, N> {
                InsertManyQuery::new(self)
            }
        }
    }
}

/// Generate query builder structs and implementations
fn gen_query_builders() -> TokenStream {
    quote! {
        /// Builder for batch INSERT statements with ON CONFLICT support
        pub struct InsertManyQuery<'a, T: QueryExt<N>, const N: usize> {
            rows: &'a [T],
            excluded_cols: Option<&'a [&'a str]>,
            on_conflict: Option<ConflictClause<'a>>,
        }

        enum ConflictClause<'a> {
            DoNothing {
                conflict_cols: &'a [&'a str],
            },
            DoUpdate {
                conflict_cols: &'a [&'a str],
                update_cols: &'a [&'a str],
            },
        }

        impl<'a, T: QueryExt<N>, const N: usize> InsertManyQuery<'a, T, N> {
            pub fn new(rows: &'a [T]) -> Self {
                Self {
                    rows,
                    excluded_cols: None,
                    on_conflict: None,
                }
            }

            /// Exclude columns from the INSERT (e.g., auto-generated columns)
            ///
            /// # Example
            /// ```rust
            /// use restaurants_col::*;
            /// rows.insert_many()
            ///     .excluding_cols(&[ID, CREATED_AT_MS, UPDATED_AT_MS])
            ///     .exec(&client)
            ///     .await?;
            /// ```
            pub fn excluding_cols(mut self, cols: &'a [&'a str]) -> Self {
                self.excluded_cols = Some(cols);
                self
            }

            /// Add ON CONFLICT DO NOTHING clause
            ///
            /// # Example
            /// ```rust
            /// use restaurants_col::*;
            /// rows.insert_many()
            ///     .on_conflict_do_nothing(&[GOOGLE_ID])
            ///     .exec(&client)
            ///     .await?;
            /// ```
            pub fn on_conflict_do_nothing(mut self, conflict_cols: &'a [&'a str]) -> Self {
                self.on_conflict = Some(ConflictClause::DoNothing {
                    conflict_cols
                });
                self
            }

            /// Add ON CONFLICT DO UPDATE clause
            ///
            /// # Example
            /// ```rust
            /// use restaurants_col::*;
            /// rows.insert_many()
            ///     .excluding_cols(&[ID, CREATED_AT_MS])
            ///     .on_conflict_do_update(
            ///         &[GOOGLE_ID],  // conflict columns (unique constraint)
            ///         &[DISPLAY_NAME, RATING, UPDATED_AT_MS],  // columns to update
            ///     )
            ///     .query(&client)  // Returns Vec<RestaurantsRow> with updated data
            ///     .await?;
            /// ```
            pub fn on_conflict_do_update(
                mut self,
                conflict_cols: &'a [&'a str],
                update_cols: &'a [&'a str],
            ) -> Self {
                self.on_conflict = Some(ConflictClause::DoUpdate {
                    conflict_cols,
                    update_cols,
                });
                self
            }

            /// Execute the INSERT statement and return the number of rows affected
            ///
            /// # Example
            /// ```rust
            /// use restaurants_col::*;
            /// let count = rows.insert_many()
            ///     .excluding_cols(&[ID])
            ///     .exec(&client)
            ///     .await?;
            /// println!("Inserted {} rows", count);
            /// ```
            pub async fn exec<C: GenericClient>(&self, client: &C) -> Result<u64, Error> {
                if self.rows.is_empty() {
                    return Ok(0);
                }

                let sql = self.build_sql();
                let params = self.build_params();
                client.execute(&sql, &params).await
            }

            /// Execute the INSERT statement and return inserted/updated rows
            ///
            /// Uses `RETURNING *` to fetch all inserted or updated data.
            ///
            /// # Example
            /// ```rust
            /// use restaurants_col::*;
            /// let inserted = rows.insert_many()
            ///     .excluding_cols(&[ID])
            ///     .query(&client)
            ///     .await?;
            ///
            /// for restaurant in inserted {
            ///     println!("Inserted with ID: {}", restaurant.id);
            /// }
            /// ```
            pub async fn query<C: GenericClient>(&self, client: &C) -> Result<Vec<T>, Error> {
                if self.rows.is_empty() {
                    return Ok(Vec::new());
                }

                let sql = self.build_sql() + " RETURNING *";
                let params = self.build_params();
                let rows = client.query(&sql, &params).await?;
                Ok(rows.into_iter().map(T::from_row).collect())
            }

            fn build_sql(&self) -> String {
                let included_cols: Vec<&str> = T::COLS
                    .iter()
                    .copied()
                    .filter(|col| !self.excluded_cols.map_or(false, |excluded| excluded.contains(col)))
                    .collect();

                let col_names = included_cols.join(", ");
                let num_cols = included_cols.len();

                let mut values_clauses = Vec::new();
                for i in 0..self.rows.len() {
                    let mut placeholders = Vec::new();
                    for j in 0..num_cols {
                        placeholders.push(format!("${}", i * num_cols + j + 1));
                    }
                    values_clauses.push(format!("({})", placeholders.join(", ")));
                }

                let mut sql = format!(
                    "INSERT INTO {} ({}) VALUES {}",
                    T::TABLE_NAME,
                    col_names,
                    values_clauses.join(", ")
                );

                if let Some(ref conflict) = self.on_conflict {
                    match conflict {
                        ConflictClause::DoNothing { conflict_cols } => {
                            sql.push_str(&format!(
                                " ON CONFLICT ({}) DO NOTHING",
                                conflict_cols.join(", ")
                            ));
                        }
                        ConflictClause::DoUpdate {
                            conflict_cols,
                            update_cols,
                        } => {
                            let updates: Vec<String> = update_cols
                                .iter()
                                .map(|col| format!("{} = EXCLUDED.{}", col, col))
                                .collect();
                            sql.push_str(&format!(
                                " ON CONFLICT ({}) DO UPDATE SET {}",
                                conflict_cols.join(", "),
                                updates.join(", ")
                            ));
                        }
                    }
                }

                sql
            }

            fn build_params(&self) -> Vec<&'a (dyn ToSql + Sync)> {
                let included_indices: Vec<usize> = T::COLS
                    .iter()
                    .enumerate()
                    .filter(|(_, col)| !self.excluded_cols.map_or(false, |excluded| excluded.contains(col)))
                    .map(|(i, _)| i)
                    .collect();

                let mut params = Vec::new();
                for row in self.rows {
                    let row_params = row.to_params();
                    for &idx in &included_indices {
                        params.push(row_params[idx]);
                    }
                }
                params
            }
        }

        /// Builder for UPDATE statements
        pub struct UpdateColsQuery<'a, T: QueryExt<N>, const N: usize> {
            row: &'a T,
            cols: &'a [&'a str],
            where_cols: Option<&'a [&'a str]>,
        }

        impl<'a, T: QueryExt<N>, const N: usize> UpdateColsQuery<'a, T, N> {
            pub fn new(row: &'a T, cols: &'a [&'a str]) -> Self {
                Self {
                    row,
                    cols,
                    where_cols: None,
                }
            }

            /// Add WHERE clause columns
            ///
            /// # Example
            /// ```rust
            /// use restaurants_col::*;
            /// restaurant
            ///     .update_cols(&[RATING, USER_RATING_COUNT])
            ///     .where_cols(&[GOOGLE_ID])
            ///     .exec(&client)
            ///     .await?;
            /// ```
            pub fn where_cols(mut self, cols: &'a [&'a str]) -> Self {
                self.where_cols = Some(cols);
                self
            }

            /// Execute the UPDATE statement and return the number of rows affected
            ///
            /// # Example
            /// ```rust
            /// use restaurants_col::*;
            /// let count = restaurant
            ///     .update_cols(&[RATING])
            ///     .where_cols(&[ID])
            ///     .exec(&client)
            ///     .await?;
            /// ```
            pub async fn exec<C: GenericClient>(&self, client: &C) -> Result<u64, Error> {
                let sql = self.build_sql();
                let params = self.build_params();
                client.execute(&sql, &params).await
            }

            fn build_sql(&self) -> String {
                let set_clauses: Vec<String> = self
                    .cols
                    .iter()
                    .enumerate()
                    .map(|(i, col)| format!("{} = ${}", col, i + 1))
                    .collect();

                let mut sql = format!(
                    "UPDATE {} SET {}",
                    T::TABLE_NAME,
                    set_clauses.join(", ")
                );

                if let Some(where_cols) = self.where_cols {
                    let where_clauses: Vec<String> = where_cols
                        .iter()
                        .enumerate()
                        .map(|(i, col)| format!("{} = ${}", col, self.cols.len() + i + 1))
                        .collect();
                    sql.push_str(&format!(" WHERE {}", where_clauses.join(" AND ")));
                }

                sql
            }

            fn build_params(&self) -> Vec<&'a (dyn ToSql + Sync)> {
                let row_params = self.row.to_params();
                let mut params = Vec::new();

                // Add SET clause params
                for col in self.cols {
                    if let Some(idx) = T::COLS.iter().position(|c| c == col) {
                        params.push(row_params[idx]);
                    }
                }

                // Add WHERE clause params
                if let Some(where_cols) = self.where_cols {
                    for col in where_cols {
                        if let Some(idx) = T::COLS.iter().position(|c| c == col) {
                            params.push(row_params[idx]);
                        }
                    }
                }

                params
            }
        }
    }
}

/// Generate column constants module for a table
fn gen_column_enum(table: &TableSchema, _config: &Config) -> TokenStream {
    let table_name_snake = table.name.to_snake_case();
    let mod_name = format_ident!("{}_col", table_name_snake);

    let const_defs: Vec<TokenStream> = table
        .columns
        .iter()
        .map(|col| {
            let const_name = format_ident!("{}", col.name.to_snake_case().to_uppercase());
            let col_name = &col.name;
            let doc = format!(" Column name for `{}`", col.name);
            quote! {
                #[doc = #doc]
                pub const #const_name: &str = #col_name;
            }
        })
        .collect();

    let doc = format!(
        " Column name constants for {}.{} table",
        table.schema, table.name
    );

    quote! {
        #[doc = #doc]
        pub mod #mod_name {
            #(#const_defs)*
        }
    }
}

/// Generate QueryExt implementation for a single table
fn gen_query_ext_impl(
    table: &TableSchema,
    _type_mappings: &HashMap<String, String>,
    config: &Config,
) -> TokenStream {
    let table_name_camel = table.name.to_upper_camel_case();
    let struct_name = format_ident!("{}{}", table_name_camel, config.tables.table_struct_suffix);

    let field_count = table.columns.len();
    let full_table_name = format!("{}.{}", table.schema, table.name);

    // Generate COLS array
    let col_names: Vec<String> = table.columns.iter().map(|col| col.name.clone()).collect();

    // Generate to_params method
    let param_refs: Vec<TokenStream> = table
        .columns
        .iter()
        .map(|col| {
            let field_name = format_ident!("{}", col.name.to_snake_case());
            quote! { &self.#field_name }
        })
        .collect();

    // Generate from_row method
    let field_extractions: Vec<TokenStream> = table
        .columns
        .iter()
        .enumerate()
        .map(|(idx, col)| {
            let field_name = format_ident!("{}", col.name.to_snake_case());
            let index = proc_macro2::Literal::usize_unsuffixed(idx);
            quote! {
                #field_name: row.get(#index)
            }
        })
        .collect();

    quote! {
        impl QueryExt<#field_count> for #struct_name {
            const COLS: [&'static str; #field_count] = [
                #(#col_names),*
            ];

            const TABLE_NAME: &'static str = #full_table_name;

            fn to_params(&self) -> [&(dyn ToSql + Sync); #field_count] {
                [#(#param_refs),*]
            }

            fn from_row(row: Row) -> Self {
                Self {
                    #(#field_extractions),*
                }
            }
        }
    }
}
