//! Code generation for batch operations (QueryExt trait + implementations)
//!
//! Generates the complete batch operations infrastructure:
//! - QueryExt trait definition
//! - Query builder structs (InsertManyQuery, UpdateColsQuery)
//! - QueryExt implementations for each table struct

use crate::config::Config;
use crate::schema_introspection::{ColumnDef, TableSchema, map_postgres_type_to_rust};
use heck::{ToSnakeCase, ToUpperCamelCase};
use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use std::collections::HashMap;

/// Generate the complete batch operations module
///
/// This includes:
/// 1. QueryExt trait definition
/// 2. Query builder structs and implementations
/// 3. QueryExt implementations for all table structs
pub fn gen_batch_ops_module(tables: &[TableSchema], config: &Config) -> TokenStream {
    if tables.is_empty() {
        return quote! {};
    }

    // Build type mappings from config
    let type_mappings: HashMap<String, String> = config
        .types
        .mapping
        .iter()
        .map(|(k, v)| {
            let rust_type = match v {
                crate::config::TypeMapping::Simple(s) => s.clone(),
                crate::config::TypeMapping::Detailed { rust_type, .. } => rust_type.clone(),
            };
            (k.clone(), rust_type)
        })
        .collect();

    let trait_def = gen_query_ext_trait();
    let builders = gen_query_builders();
    let col_enums: Vec<TokenStream> = tables
        .iter()
        .map(|table| gen_column_enum(table, config))
        .collect();

    // Separate batch structs from trait implementations
    let batch_structs: Vec<TokenStream> = tables
        .iter()
        .map(|table| gen_batch_struct(table, &type_mappings, config))
        .collect();

    let trait_impls: Vec<TokenStream> = tables
        .iter()
        .map(|table| gen_query_ext_impl_only(table, &type_mappings, config))
        .collect();

    quote! {
        //! Auto-generated batch operations infrastructure
        //! DO NOT EDIT - Regenerated by Clorinde
        //!
        //! This module provides:
        //! - QueryExt trait for batch database operations
        //! - Query builders (InsertManyQuery, UpdateColsQuery)
        //! - QueryExt implementations for all table structs

        use tokio_postgres::{Row, types::ToSql, Error};
        use crate::client::async_::GenericClient;
        use crate::tables::*;
        use itertools::Itertools;

        #(#col_enums)*

        /// Column name constants and batch operation infrastructure
        ///
        /// This module is intentionally named `__private` to discourage direct use.
        /// Users should access it through the public trait methods instead.
        pub mod __private {
            use super::*;

            #trait_def

            #builders

            #(#trait_impls)*
        }

        // Re-export the trait for easy access
        pub use __private::QueryExt;

        // Batch operation structs are public
        #(#batch_structs)*
    }
}

/// Generate the QueryExt trait definition
fn gen_query_ext_trait() -> TokenStream {
    quote! {
        /// Trait for database table structs to enable batch operations
        ///
        /// Generic parameter N is the number of columns in the table.
        pub trait QueryExt<const N: usize>: Sized + Sync {
            /// SQL table name (e.g., "public.places")
            const TABLE_NAME: &'static str;

            /// All column names in ordinal order
            const COLS: [&'static str; N];

            /// Convert struct fields to SQL parameters
            fn to_params(&self) -> [&(dyn ToSql + Sync); N];

            /// Construct struct from database row
            fn from_row(row: Row) -> Self;

            /// Insert a single row and return it with database-generated values
            ///
            /// Uses `RETURNING *` to fetch the complete inserted row.
            ///
            /// # Example
            /// ```rust
            /// let inserted = place.insert(&client).await?;
            /// println!("Inserted with ID: {}", inserted.id);
            /// ```
            fn insert<C: GenericClient>(&self, client: &C) -> impl std::future::Future<Output = Result<Self, Error>> + Send {
                async move {
                    let col_names = Self::COLS.join(", ");
                    let placeholders: Vec<String> = (1..=N).map(|i| format!("${}", i)).collect();
                    let sql = format!(
                        "INSERT INTO {} ({}) VALUES ({}) RETURNING *",
                        Self::TABLE_NAME,
                        col_names,
                        placeholders.join(", ")
                    );
                    let params = self.to_params();
                    let row = client.query_one(&sql, &params).await?;
                    Ok(Self::from_row(row))
                }
            }

            /// Start building an UPDATE statement
            ///
            /// # Example
            /// ```rust
            /// use places_col::*;
            ///
            /// place
            ///     .update_cols(&[RATING, USER_RATING_COUNT])
            ///     .where_cols(&[GOOGLE_ID])
            ///     .exec(&client)
            ///     .await?;
            /// ```
            fn update_cols<'a>(&'a self, cols: &'a [&'a str]) -> UpdateColsQuery<'a, Self, N> {
                UpdateColsQuery::new(self, cols)
            }
        }
    }
}

/// Generate extension trait for Vec/slices and wrapper for rows

/// Generate query builder structs and implementations
fn gen_query_builders() -> TokenStream {
    quote! {
        /// Builder for UPDATE statements
        pub struct UpdateColsQuery<'a, T: QueryExt<N>, const N: usize> {
            row: &'a T,
            cols: &'a [&'a str],
            where_cols: Option<&'a [&'a str]>,
        }

        impl<'a, T: QueryExt<N>, const N: usize> UpdateColsQuery<'a, T, N> {
            pub fn new(row: &'a T, cols: &'a [&'a str]) -> Self {
                Self {
                    row,
                    cols,
                    where_cols: None,
                }
            }

            /// Add WHERE clause columns
            ///
            /// # Example
            /// ```rust
            /// use places_col::*;
            /// place
            ///     .update_cols(&[RATING, USER_RATING_COUNT])
            ///     .where_cols(&[GOOGLE_ID])
            ///     .exec(&client)
            ///     .await?;
            /// ```
            pub fn where_cols(mut self, cols: &'a [&'a str]) -> Self {
                self.where_cols = Some(cols);
                self
            }

            /// Execute the UPDATE statement and return the number of rows affected
            ///
            /// # Example
            /// ```rust
            /// use places_col::*;
            /// let count = place
            ///     .update_cols(&[RATING])
            ///     .where_cols(&[ID])
            ///     .exec(&client)
            ///     .await?;
            /// ```
            pub async fn exec<C: GenericClient>(&self, client: &C) -> Result<u64, Error> {
                let sql = self.build_sql();
                let params = self.build_params();
                client.execute(&sql, &params).await
            }

            fn build_sql(&self) -> String {
                let set_clauses: Vec<String> = self
                    .cols
                    .iter()
                    .enumerate()
                    .map(|(i, col)| format!("{} = ${}", col, i + 1))
                    .collect();

                let mut sql = format!(
                    "UPDATE {} SET {}",
                    T::TABLE_NAME,
                    set_clauses.join(", ")
                );

                if let Some(where_cols) = self.where_cols {
                    let where_clauses: Vec<String> = where_cols
                        .iter()
                        .enumerate()
                        .map(|(i, col)| format!("{} = ${}", col, self.cols.len() + i + 1))
                        .collect();
                    sql.push_str(&format!(" WHERE {}", where_clauses.join(" AND ")));
                }

                sql
            }

            fn build_params(&self) -> Vec<&'a (dyn ToSql + Sync)> {
                let row_params = self.row.to_params();
                let mut params = Vec::new();

                // Add SET clause params
                for col in self.cols {
                    if let Some(idx) = T::COLS.iter().position(|c| c == col) {
                        params.push(row_params[idx]);
                    }
                }

                // Add WHERE clause params
                if let Some(where_cols) = self.where_cols {
                    for col in where_cols {
                        if let Some(idx) = T::COLS.iter().position(|c| c == col) {
                            params.push(row_params[idx]);
                        }
                    }
                }

                params
            }
        }
    }
}

fn map_column_to_pg_type(col: &ColumnDef) -> String {
    if col.data_type == "ARRAY" {
        let elem = col.udt_name.strip_prefix('_').unwrap_or(&col.udt_name);
        return format!("{}[]", elem);
    }

    if col.data_type == "USER-DEFINED" {
        return col.udt_name.clone();
    }

    col.udt_name.clone()
}

/// Generate column constants module for a table
fn gen_column_enum(table: &TableSchema, _config: &Config) -> TokenStream {
    let table_name_snake = table.name.to_snake_case();
    let mod_name = format_ident!("{}_col", table_name_snake);

    let const_defs: Vec<TokenStream> = table
        .columns
        .iter()
        .map(|col| {
            let const_name = format_ident!("{}", col.name.to_snake_case().to_uppercase());
            let col_name = &col.name;
            let doc = format!(" Column name for `{}`", col.name);
            quote! {
                #[doc = #doc]
                pub const #const_name: &str = #col_name;
            }
        })
        .collect();

    let doc = format!(
        " Column name constants for {}.{} table",
        table.schema, table.name
    );

    quote! {
        #[doc = #doc]
        pub mod #mod_name {
            #(#const_defs)*
        }
    }
}

/// Generate QueryExt implementation for a single table
fn gen_query_ext_impl(
    table: &TableSchema,
    type_mappings: &HashMap<String, String>,
    config: &Config,
) -> TokenStream {
    let table_name_camel = table.name.to_upper_camel_case();
    let struct_name = format_ident!("{}{}", table_name_camel, config.tables.table_struct_suffix);
    let batch_struct_name = format_ident!("{}Batch", table_name_camel);

    let field_count = table.columns.len();
    let full_table_name = format!("{}.{}", table.schema, table.name);

    // Generate COLS array
    let col_names: Vec<String> = table.columns.iter().map(|col| col.name.clone()).collect();
    // Generate to_params method
    let param_refs: Vec<TokenStream> = table
        .columns
        .iter()
        .map(|col| {
            let field_name = format_ident!("{}", col.name.to_snake_case());
            quote! { &self.#field_name }
        })
        .collect();

    // Generate from_row method
    let field_extractions: Vec<TokenStream> = table
        .columns
        .iter()
        .enumerate()
        .map(|(idx, col)| {
            let field_name = format_ident!("{}", col.name.to_snake_case());
            let index = proc_macro2::Literal::usize_unsuffixed(idx);
            quote! {
                #field_name: row.get(#index)
            }
        })
        .collect();

    let batch_fields: Vec<TokenStream> = table
        .columns
        .iter()
        .map(|col| {
            let field_name = format_ident!("{}", col.name.to_snake_case());
            let rust_type_str = map_postgres_type_to_rust(col, type_mappings);
            let vec_type_str = format!("Vec<{}>", rust_type_str);
            let vec_type: syn::Type = syn::parse_str(&vec_type_str)
                .unwrap_or_else(|_| syn::parse_str("Vec<String>").unwrap());

            quote! { pub #field_name: #vec_type }
        })
        .collect();

    let batch_init_fields: Vec<TokenStream> = table
        .columns
        .iter()
        .map(|col| {
            let field_name = format_ident!("{}", col.name.to_snake_case());
            quote! { #field_name: Vec::new() }
        })
        .collect();
    let batch_init_fields_with_capacity: Vec<TokenStream> = table
        .columns
        .iter()
        .map(|col| {
            let field_name = format_ident!("{}", col.name.to_snake_case());
            quote! { #field_name: Vec::with_capacity(capacity) }
        })
        .collect();

    // Generate individual named parameters for push method
    let push_params: Vec<TokenStream> = table
        .columns
        .iter()
        .enumerate()
        .map(|(idx, col)| {
            let field_name = format_ident!("{}", col.name.to_snake_case());
            let rust_type_str = map_postgres_type_to_rust(col, type_mappings);
            let rust_type: syn::Type = syn::parse_str(&rust_type_str)
                .unwrap_or_else(|_| syn::parse_str("String").unwrap());
            let generic_name = format_ident!("T{}", idx);

            // Non-default/non-identity columns: regular type
            // Default/identity columns: impl Into<Option<T>>
            if col.column_default.is_none() && !col.is_identity {
                quote! { #field_name: #rust_type }
            } else {
                quote! { #field_name: #generic_name }
            }
        })
        .collect();

    // Generate generic bounds for nullable, default, or identity columns
    let push_generics: Vec<TokenStream> = table
        .columns
        .iter()
        .enumerate()
        .filter_map(|(idx, col)| {
            if col.column_default.is_some() || col.is_identity {
                let rust_type_str = map_postgres_type_to_rust(col, type_mappings);
                let rust_type: syn::Type = syn::parse_str(&rust_type_str)
                    .unwrap_or_else(|_| syn::parse_str("String").unwrap());
                let generic_name = format_ident!("T{}", idx);
                Some(quote! { #generic_name: Into<Option<#rust_type>> })
            } else {
                None
            }
        })
        .collect();

    let push_field_pushes: Vec<TokenStream> = table
        .columns
        .iter()
        .map(|col| {
            let field_name = format_ident!("{}", col.name.to_snake_case());

            if col.column_default.is_none() && !col.is_identity {
                // Non-default columns: push directly
                quote! {
                    self.#field_name.push(#field_name);
                }
            } else {
                // Default/identity columns: use Into<Option<T>>
                quote! {
                    if let Some(val) = #field_name.into() {
                        self.#field_name.push(val);
                    }
                }
            }
        })
        .collect();

    let first_field_name = table
        .columns
        .iter()
        // Prefer a required (non-default, non-identity) column for is_empty/len checks
        // because optional/default columns may be omitted in push() and stay empty.
        .find(|col| !col.is_identity && col.column_default.is_none())
        .or_else(|| table.columns.iter().find(|col| !col.is_identity))
        .or_else(|| table.columns.first())
        .map(|col| format_ident!("{}", col.name.to_snake_case()))
        .expect("table must have at least one column");

    // Build complete tuples (col_name, col_type, param) as TokenStreams for filtering case
    let col_name_type_param_tuples: Vec<TokenStream> = table
        .columns
        .iter()
        .map(|col| {
            let col_name = &col.name;
            let col_pg_type = map_column_to_pg_type(col);
            let col_type = format!("{}[]", col_pg_type);
            let field_name = format_ident!("{}", col.name.to_snake_case());
            quote! {
                (#col_name, #col_type, &self.#field_name as &(dyn ToSql + Sync))
            }
        })
        .collect();

    // Generate match arms to get Vec length by index
    let idx_to_len_arms: Vec<TokenStream> = table
        .columns
        .iter()
        .enumerate()
        .map(|(idx, col)| {
            let field_name = format_ident!("{}", col.name.to_snake_case());
            let idx_lit = proc_macro2::Literal::usize_unsuffixed(idx);
            quote! {
                #idx_lit => self.#field_name.len(),
            }
        })
        .collect();

    let struct_doc = format!(
        " Batch insert builder for {} using UNNEST\n\n \
         Usage: Required columns accept values directly. Optional columns (with DEFAULT or IDENTITY) \
         accept impl Into<Option<T>>, so you can pass the value, Some(value), or None.\n\n \
         Example:\n \
         ```rust\n \
         let mut batch = {}Batch::new();\n \
         // Required columns: pass values directly\n \
         // Optional columns: pass value, Some(value), or None\n \
         batch.push(\"name\", \"email\", None, None);\n \
         batch.push(\"name2\", \"email2\", Some(100), Some(4.5));\n \
         batch.exec(&client).await?;\n \
         ```\n\n \
         Validation: All non-empty column Vecs must have the same length. \
         Panics if lengths don't match.",
        struct_name, struct_name
    );

    quote! {
        #[doc = #struct_doc]
        pub struct #batch_struct_name {
            #(#batch_fields,)*
        }

        impl #batch_struct_name {
            pub fn new() -> Self {
                Self {
                    #(#batch_init_fields,)*
                }
            }

            pub fn with_capacity(capacity: usize) -> Self {
                Self {
                    #(#batch_init_fields_with_capacity,)*
                }
            }

            /// Add values to the batch
            ///
            /// Required columns (without defaults) accept values directly.
            /// Optional columns (with DEFAULT or IDENTITY) accept `impl Into<Option<T>>`,
            /// so you can pass the value directly, `Some(value)`, or `None`.
            ///
            /// # Example
            /// ```rust
            /// // Push with all required values
            /// batch.push("google_id", location, h3_cell, None, None);
            ///
            /// // Or provide optional values
            /// batch.push("google_id", location, h3_cell, Some(4.5), Some(100));
            /// ```
            pub fn push<#(#push_generics),*>(
                &mut self,
                #(#push_params),*
            ) -> &mut Self {
                #(#push_field_pushes)*
                self
            }

            pub fn is_empty(&self) -> bool {
                self.#first_field_name.is_empty()
            }

            pub fn len(&self) -> usize {
                self.#first_field_name.len()
            }

            pub async fn exec<C: GenericClient>(&self, client: &C) -> Result<u64, Error> {
                if self.is_empty() {
                    return Ok(0);
                }

                // Build tuple array for all columns
                let all_cols: [(&str, &str, &(dyn ToSql + Sync)); #field_count] = [
                    #(#col_name_type_param_tuples),*
                ];

                // Filter to non-empty columns and validate all have same length
                let non_empty: Vec<_> = all_cols
                    .into_iter()
                    .enumerate()
                    .filter_map(|(idx, (col_name, col_type, param))| {
                        let len = match idx {
                            #(#idx_to_len_arms)*
                            _ => 0,
                        };
                        if len > 0 {
                            Some((col_name, col_type, param, len))
                        } else {
                            None
                        }
                    })
                    .collect();

                if non_empty.is_empty() {
                    return Ok(0);
                }

                // Validate all non-empty columns have the same length
                let first_len = non_empty[0].3;
                for (col_name, _, _, len) in &non_empty {
                    if *len != first_len {
                        panic!(
                            "Batch insert validation failed: Column '{}' has {} values, but expected {} (first non-empty column length)",
                            col_name, len, first_len
                        );
                    }
                }

                let col_names_joined = non_empty.iter().map(|(name, _, _, _)| *name).join(", ");
                let params: Vec<_> = non_empty.iter().map(|(_, _, param, _)| *param).collect();
                let unnest_args_joined = non_empty
                    .iter()
                    .enumerate()
                    .map(|(idx, (_, col_type, _, _))| format!("${}::{}", idx + 1, col_type))
                    .join(", ");

                let sql = format!(
                    "INSERT INTO {} ({}) SELECT * FROM UNNEST({}) AS t({})",
                    #full_table_name, col_names_joined, unnest_args_joined, col_names_joined
                );

                client.execute(&sql, &params).await
            }
        }

        impl #struct_name {
            pub fn batch() -> #batch_struct_name {
                #batch_struct_name::new()
            }

            pub fn batch_with_capacity(capacity: usize) -> #batch_struct_name {
                #batch_struct_name::with_capacity(capacity)
            }
        }

        impl QueryExt<#field_count> for #struct_name {
            const COLS: [&'static str; #field_count] = [
                #(#col_names),*
            ];

            const TABLE_NAME: &'static str = #full_table_name;

            fn to_params(&self) -> [&(dyn ToSql + Sync); #field_count] {
                [#(#param_refs),*]
            }

            fn from_row(row: Row) -> Self {
                Self {
                    #(#field_extractions),*
                }
            }
        }
    }
}

/// Generate only the batch struct (no trait implementation)
fn gen_batch_struct(
    table: &TableSchema,
    type_mappings: &HashMap<String, String>,
    config: &Config,
) -> TokenStream {
    let table_name_camel = table.name.to_upper_camel_case();
    let struct_name = format_ident!("{}{}", table_name_camel, config.tables.table_struct_suffix);
    let batch_struct_name = format_ident!("{}Batch", table_name_camel);
    let full_table_name = format!("{}.{}", table.schema, table.name);

    let batch_fields: Vec<TokenStream> = table
        .columns
        .iter()
        .map(|col| {
            let field_name = format_ident!("{}", col.name.to_snake_case());
            let rust_type_str = map_postgres_type_to_rust(col, type_mappings);
            let rust_type: syn::Type = syn::parse_str(&rust_type_str)
                .unwrap_or_else(|_| syn::parse_str("String").unwrap());
            quote! { pub #field_name: Vec<#rust_type> }
        })
        .collect();

    let batch_init_fields: Vec<TokenStream> = table
        .columns
        .iter()
        .map(|col| {
            let field_name = format_ident!("{}", col.name.to_snake_case());
            quote! { #field_name: Vec::new() }
        })
        .collect();

    let batch_init_fields_with_capacity: Vec<TokenStream> = table
        .columns
        .iter()
        .map(|col| {
            let field_name = format_ident!("{}", col.name.to_snake_case());
            quote! { #field_name: Vec::with_capacity(capacity) }
        })
        .collect();

    // Generate individual named parameters for push method
    let push_params: Vec<TokenStream> = table
        .columns
        .iter()
        .map(|col| {
            let field_name = format_ident!("{}", col.name.to_snake_case());
            let rust_type_str = map_postgres_type_to_rust(col, type_mappings);
            let rust_type: syn::Type = syn::parse_str(&rust_type_str)
                .unwrap_or_else(|_| syn::parse_str("String").unwrap());
            let generic_name = format_ident!("{}", col.name.to_upper_camel_case());

            // Non-default/non-identity columns: regular type
            // Default/identity columns: impl Into<Option<T>>
            if col.column_default.is_none() && !col.is_identity {
                quote! { #field_name: #rust_type }
            } else {
                // If the column is nullable, we use the type directly (Option<T>)
                // If it's NOT nullable but has a default (e.g. created_at), we use Into<Option<T>>
                if col.is_nullable {
                    quote! { #field_name: #rust_type }
                } else {
                    quote! { #field_name: #generic_name }
                }
            }
        })
        .collect();

    // Generate generic bounds for default/identity columns only
    let push_generics: Vec<TokenStream> = table
        .columns
        .iter()
        .filter_map(|col| {
            // Only generate generic param if it has default AND is NOT nullable
            // Nullable columns with default just get Option<T> directly
            if (col.column_default.is_some() || col.is_identity) && !col.is_nullable {
                let rust_type_str = map_postgres_type_to_rust(col, type_mappings);
                let rust_type: syn::Type = syn::parse_str(&rust_type_str)
                    .unwrap_or_else(|_| syn::parse_str("String").unwrap());
                let generic_name = format_ident!("{}", col.name.to_upper_camel_case());
                Some(quote! { #generic_name: Into<Option<#rust_type>> })
            } else {
                None
            }
        })
        .collect();

    let push_field_pushes: Vec<TokenStream> = table
        .columns
        .iter()
        .map(|col| {
            let field_name = format_ident!("{}", col.name.to_snake_case());

            if col.column_default.is_none() && !col.is_identity {
                // Non-default columns: push directly
                quote! {
                    self.#field_name.push(#field_name);
                }
            } else {
                // Default/identity columns
                if col.is_nullable {
                    // Nullable with default: push directly (it's already Option<T>)
                    // If None is passed, we push None, which inserts NULL (overriding default)
                    quote! {
                        self.#field_name.push(#field_name);
                    }
                } else {
                    // Non-nullable with default: use Into<Option<T>> logic
                    // If None is passed, we skip pushing to the Vec.
                    // Important: For a batch, you must either provide the column for all rows, or for none.
                    // Mixing Some and None across rows will cause length mismatch validation failure.
                    quote! {
                        if let Some(val) = #field_name.into() {
                            self.#field_name.push(val);
                        }
                    }
                }
            }
        })
        .collect();

    let first_field_name = table
        .columns
        .iter()
        // Prefer a required (non-default, non-identity) column for is_empty/len checks
        // because optional/default columns may be omitted in push() and stay empty.
        .find(|col| !col.is_identity && col.column_default.is_none())
        .or_else(|| table.columns.iter().find(|col| !col.is_identity))
        .or_else(|| table.columns.first())
        .map(|col| format_ident!("{}", col.name.to_snake_case()))
        .expect("Table must have at least one column");

    let array_col_specs: Vec<TokenStream> = table
        .columns
        .iter()
        .map(|col| {
            let col_name = &col.name;
            let field_name = format_ident!("{}", col.name.to_snake_case());
            let pg_type = map_column_to_pg_type(col);
            let pg_array_type = format!("{}[]", pg_type);
            quote! {
                (#col_name, #pg_array_type, &self.#field_name as &(dyn ToSql + Sync))
            }
        })
        .collect();

    let idx_to_len_arms: Vec<TokenStream> = table
        .columns
        .iter()
        .enumerate()
        .map(|(idx, col)| {
            let field_name = format_ident!("{}", col.name.to_snake_case());
            let idx_lit = proc_macro2::Literal::usize_unsuffixed(idx);
            quote! {
                #idx_lit => self.#field_name.len(),
            }
        })
        .collect();

    let push_generics_clause = if push_generics.is_empty() {
        quote! {}
    } else {
        quote! { <#(#push_generics),*> }
    };

    let field_count = table.columns.len();

    let field_count = table.columns.len();

    // Identify required vs optional columns for better docs
    let (required_cols, optional_cols): (Vec<_>, Vec<_>) = table
        .columns
        .iter()
        .partition(|col| col.column_default.is_none() && !col.is_identity);

    let optional_col_names = if optional_cols.is_empty() {
        "None".to_string()
    } else {
        optional_cols
            .iter()
            .map(|c| format!("\n - {}", c.name))
            .collect::<String>()
    };

    let example_args = table
        .columns
        .iter()
        .map(|col| {
            if col.column_default.is_some() || col.is_identity {
                "None"
            } else {
                // Required: provide a dummy value based on type
                match col.data_type.as_str() {
                    "integer" | "bigint" | "smallint" => "1",
                    "double precision" | "real" | "numeric" => "1.0",
                    "boolean" => "true",
                    "text" | "varchar" | "char" => "\"value\".to_string()",
                    "uuid" => "uuid::Uuid::new_v4()",
                    "json" | "jsonb" => "serde_json::json!({})",
                    _ => "\"value\".to_string()", // Fallback
                }
            }
        })
        .collect::<Vec<_>>()
        .join(", ");

    let usage_doc = format!(
        " Batch insert builder for {0} using UNNEST\n\n \
         Columns with defaults/identity can be omitted by passing `None` (for all rows in the batch).\n\n \
         **Optional columns:** {1}\n\n \
         Usage:\n \
         ```rust\n \
         let mut batch = {0}Batch::new();\n \
         batch.push({2});\n \
         batch.exec(&client).await?;\n \
         ```\n\n \
         Validation: All non-empty column Vecs must have the same length. Panics if lengths don't match.",
        table_name_camel, optional_col_names, example_args
    );

    quote! {
        #[doc = #usage_doc]
        pub struct #batch_struct_name {
            #(#batch_fields),*,
            _conflict_target: Option<&'static [&'static str]>,
            _do_update_cols: Option<&'static [&'static str]>,
        }

        impl #batch_struct_name {
            pub fn new() -> Self {
                Self {
                    #(#batch_init_fields),*,
                    _conflict_target: None,
                    _do_update_cols: None,
                }
            }

            pub fn with_capacity(capacity: usize) -> Self {
                Self {
                    #(#batch_init_fields_with_capacity),*,
                    _conflict_target: None,
                    _do_update_cols: None,
                }
            }

            #[doc = #usage_doc]
            pub fn push #push_generics_clause (
                &mut self,
                #(#push_params),*
            ) -> &mut Self {
                #(#push_field_pushes)*
                self
            }

            pub fn on_conflict_do_nothing(&mut self, target_cols: &'static [&'static str]) -> &mut Self {
                self._conflict_target = Some(target_cols);
                self._do_update_cols = None;
                self
            }

            pub fn on_conflict_do_update(&mut self, target_cols: &'static [&'static str], update_cols: &'static [&'static str]) -> &mut Self {
                self._conflict_target = Some(target_cols);
                self._do_update_cols = Some(update_cols);
                self
            }

            pub fn is_empty(&self) -> bool {
                self.#first_field_name.is_empty()
            }

            pub fn len(&self) -> usize {
                self.#first_field_name.len()
            }

            fn prepare_sql(&self) -> (String, Vec<&(dyn ToSql + Sync)>) {
                if self.is_empty() {
                    return ("".to_string(), vec![]);
                }

                let all_cols: [(&str, &str, &(dyn ToSql + Sync)); #field_count] = [
                    #(#array_col_specs),*
                ];

                let non_empty: Vec<_> = all_cols
                    .into_iter()
                    .enumerate()
                    .filter_map(|(idx, (col_name, col_type, param))| {
                        let len = match idx {
                            #(#idx_to_len_arms)*
                            _ => 0,
                        };
                        if len > 0 {
                            Some((col_name, col_type, param, len))
                        } else {
                            None
                        }
                    })
                    .collect();

                if non_empty.is_empty() {
                    return ("".to_string(), vec![]);
                }

                // Validate all non-empty columns have the same length
                let first_len = non_empty[0].3;
                for (col_name, _, _, len) in &non_empty {
                    if *len != first_len {
                        panic!(
                            "Batch insert validation failed: Column '{}' has {} values, but expected {} (first non-empty column length)",
                            col_name, len, first_len
                        );
                    }
                }

                let col_names_joined = non_empty.iter().map(|(name, _, _, _)| *name).join(", ");
                let params: Vec<_> = non_empty.iter().map(|(_, _, param, _)| *param).collect();
                let unnest_args_joined = non_empty
                    .iter()
                    .enumerate()
                    .map(|(idx, (_, col_type, _, _))| format!("${}::{}", idx + 1, col_type))
                    .join(", ");

                let mut sql = format!(
                    "INSERT INTO {} ({}) SELECT * FROM UNNEST({}) AS t({})",
                    #full_table_name, col_names_joined, unnest_args_joined, col_names_joined
                );

                if let Some(target) = self._conflict_target {
                    let target_str = target.join(", ");
                    sql.push_str(&format!(" ON CONFLICT ({})", target_str));

                    if let Some(update_cols) = self._do_update_cols {
                        let update_set: Vec<String> = update_cols.iter()
                            .map(|col| format!("{} = EXCLUDED.{}", col, col))
                            .collect();
                        sql.push_str(&format!(" DO UPDATE SET {}", update_set.join(", ")));
                    } else {
                        sql.push_str(" DO NOTHING");
                    }
                }

                (sql, params)
            }

            pub async fn exec<C: GenericClient>(&self, client: &C) -> Result<u64, Error> {
                let (sql, params) = self.prepare_sql();
                if sql.is_empty() {
                    return Ok(0);
                }
                client.execute(&sql, &params).await
            }

            pub async fn query<C: GenericClient>(&self, client: &C) -> Result<Vec<#struct_name>, Error> {
                let (mut sql, params) = self.prepare_sql();
                if sql.is_empty() {
                    return Ok(vec![]);
                }

                sql.push_str(" RETURNING *");

                let rows = client.query(&sql, &params).await?;
                Ok(rows.into_iter().map(#struct_name::from_row).collect())
            }
        }
    }
}

/// Generate only the QueryExt trait implementation (no batch struct)
fn gen_query_ext_impl_only(
    table: &TableSchema,
    type_mappings: &HashMap<String, String>,
    config: &Config,
) -> TokenStream {
    let table_name_camel = table.name.to_upper_camel_case();
    let struct_name = format_ident!("{}{}", table_name_camel, config.tables.table_struct_suffix);
    let batch_struct_name = format_ident!("{}Batch", table_name_camel);

    let field_count = table.columns.len();
    let full_table_name = format!("{}.{}", table.schema, table.name);

    // Generate COLS array
    let col_names: Vec<String> = table.columns.iter().map(|col| col.name.clone()).collect();

    // Generate to_params method
    let param_refs: Vec<TokenStream> = table
        .columns
        .iter()
        .map(|col| {
            let field_name = format_ident!("{}", col.name.to_snake_case());
            quote! { &self.#field_name }
        })
        .collect();

    // Generate from_row method
    let field_extractions: Vec<TokenStream> = table
        .columns
        .iter()
        .enumerate()
        .map(|(idx, col)| {
            let field_name = format_ident!("{}", col.name.to_snake_case());
            let index = proc_macro2::Literal::usize_unsuffixed(idx);
            quote! {
                #field_name: row.get(#index)
            }
        })
        .collect();

    quote! {
        impl #struct_name {
            pub fn batch() -> #batch_struct_name {
                #batch_struct_name::new()
            }

            pub fn batch_with_capacity(capacity: usize) -> #batch_struct_name {
                #batch_struct_name::with_capacity(capacity)
            }
        }

        impl QueryExt<#field_count> for #struct_name {
            const COLS: [&'static str; #field_count] = [
                #(#col_names),*
            ];

            const TABLE_NAME: &'static str = #full_table_name;

            fn to_params(&self) -> [&(dyn ToSql + Sync); #field_count] {
                [#(#param_refs),*]
            }

            fn from_row(row: Row) -> Self {
                Self {
                    #(#field_extractions),*
                }
            }
        }
    }
}
