//! Code generation for batch operations (QueryExt trait + implementations)
//!
//! Generates the complete batch operations infrastructure:
//! - QueryExt trait definition
//! - Query builder structs (InsertManyQuery, UpdateColsQuery)
//! - QueryExt implementations for each table struct

use crate::config::Config;
use crate::schema_introspection::TableSchema;
use heck::{ToSnakeCase, ToUpperCamelCase};
use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use std::collections::HashMap;

/// Generate the complete batch operations module
///
/// This includes:
/// 1. QueryExt trait definition
/// 2. Query builder structs and implementations
/// 3. QueryExt implementations for all table structs
pub fn gen_batch_ops_module(tables: &[TableSchema], config: &Config) -> TokenStream {
    if tables.is_empty() {
        return quote! {};
    }

    // Build type mappings from config
    let type_mappings: HashMap<String, String> = config
        .types
        .mapping
        .iter()
        .map(|(k, v)| {
            let rust_type = match v {
                crate::config::TypeMapping::Simple(s) => s.clone(),
                crate::config::TypeMapping::Detailed { rust_type, .. } => rust_type.clone(),
            };
            (k.clone(), rust_type)
        })
        .collect();

    let trait_def = gen_query_ext_trait();
    let builders = gen_query_builders();
    let col_enums: Vec<TokenStream> = tables
        .iter()
        .map(|table| gen_column_enum(table, config))
        .collect();
    let impls: Vec<TokenStream> = tables
        .iter()
        .map(|table| gen_query_ext_impl(table, &type_mappings, config))
        .collect();

    let slice_ext = gen_slice_ext_trait();

    quote! {
        //! Auto-generated batch operations infrastructure
        //! DO NOT EDIT - Regenerated by Clorinde
        //!
        //! This module provides:
        //! - QueryExt trait for batch database operations
        //! - Query builders (InsertManyQuery, UpdateColsQuery)
        //! - QueryExt implementations for all table structs

        use tokio_postgres::{Row, types::ToSql, Error};
        use crate::client::async_::GenericClient;
        use crate::tables::*;

        #(#col_enums)*

        /// Column name constants and batch operation infrastructure
        ///
        /// This module is intentionally named `__private` to discourage direct use.
        /// Users should access it through the public trait methods instead.
        pub mod __private {
            use super::*;

            #trait_def

            #slice_ext

            #builders

            #(#impls)*
        }

        // Re-export the traits for easy access
        pub use __private::{QueryExt, BatchInsertExt};
    }
}

/// Generate the QueryExt trait definition
fn gen_query_ext_trait() -> TokenStream {
    quote! {
        /// Trait for database table structs to enable batch operations
        ///
        /// Generic parameter N is the number of columns in the table.
        pub trait QueryExt<const N: usize>: Sized + Sync {
            /// SQL table name (e.g., "public.places")
            const TABLE_NAME: &'static str;

            /// All column names in ordinal order
            const COLS: [&'static str; N];

            /// Convert struct fields to SQL parameters
            fn to_params(&self) -> [&(dyn ToSql + Sync); N];

            /// Construct struct from database row
            fn from_row(row: Row) -> Self;

            /// Insert a single row and return it with database-generated values
            ///
            /// Uses `RETURNING *` to fetch the complete inserted row.
            ///
            /// # Example
            /// ```rust
            /// let inserted = place.insert(&client).await?;
            /// println!("Inserted with ID: {}", inserted.id);
            /// ```
            fn insert<C: GenericClient>(&self, client: &C) -> impl std::future::Future<Output = Result<Self, Error>> + Send {
                async move {
                    let col_names = Self::COLS.join(", ");
                    let placeholders: Vec<String> = (1..=N).map(|i| format!("${}", i)).collect();
                    let sql = format!(
                        "INSERT INTO {} ({}) VALUES ({}) RETURNING *",
                        Self::TABLE_NAME,
                        col_names,
                        placeholders.join(", ")
                    );
                    let params = self.to_params();
                    let row = client.query_one(&sql, &params).await?;
                    Ok(Self::from_row(row))
                }
            }

            /// Start building a batch INSERT statement
            ///
            /// Accepts slices, vectors, and anything convertible to InsertManyRows.
            /// For owned iterators, use the .insert_many() extension method instead.
            ///
            /// # Example
            /// ```rust
            /// use places_col::*;
            ///
            /// let rows = vec![restaurant1, restaurant2];
            ///
            /// // Insert with auto-generated columns excluded
            /// PlacesRow::insert_many(&rows)
            ///     .excluding_cols(&[ID, CREATED_AT_MS, UPDATED_AT_MS])
            ///     .exec(&client)
            ///     .await?;
            ///
            /// // Upsert on conflict
            /// PlacesRow::insert_many(&rows)
            ///     .excluding_cols(&[ID, CREATED_AT_MS])
            ///     .on_conflict_do_update(
            ///         &[GOOGLE_ID],  // conflict columns
            ///         &[DISPLAY_NAME, RATING],  // columns to update
            ///     )
            ///     .query(&client)  // Returns inserted/updated rows
            ///     .await?;
            /// ```
            fn insert_many<'a>(rows: impl Into<InsertManyRows<'a, Self, N>>) -> InsertManyQuery<'a, Self, N> {
                InsertManyQuery::new(rows.into())
            }

            /// Start building an UPDATE statement
            ///
            /// # Example
            /// ```rust
            /// use places_col::*;
            ///
            /// place
            ///     .update_cols(&[RATING, USER_RATING_COUNT])
            ///     .where_cols(&[GOOGLE_ID])
            ///     .exec(&client)
            ///     .await?;
            /// ```
            fn update_cols<'a>(&'a self, cols: &'a [&'a str]) -> UpdateColsQuery<'a, Self, N> {
                UpdateColsQuery::new(self, cols)
            }
        }
    }
}

/// Generate extension trait for Vec/slices and wrapper for rows
fn gen_slice_ext_trait() -> TokenStream {
    quote! {
        /// Wrapper that avoids collecting iterators until absolutely necessary
        pub enum InsertManyRows<'a, T: QueryExt<N>, const N: usize> {
            Slice(&'a [T]),
            OwnedVec(Vec<T>),
        }

        impl<'a, T: QueryExt<N>, const N: usize> InsertManyRows<'a, T, N> {
            pub fn as_slice(&'a self) -> &'a [T] {
                match self {
                    InsertManyRows::Slice(s) => s,
                    InsertManyRows::OwnedVec(v) => v.as_slice(),
                }
            }
        }

        impl<'a, T: QueryExt<N>, const N: usize> From<&'a [T]> for InsertManyRows<'a, T, N> {
            fn from(slice: &'a [T]) -> Self {
                InsertManyRows::Slice(slice)
            }
        }

        impl<'a, T: QueryExt<N>, const N: usize> From<&'a Vec<T>> for InsertManyRows<'a, T, N> {
            fn from(vec: &'a Vec<T>) -> Self {
                InsertManyRows::Slice(vec.as_slice())
            }
        }

        impl<'a, T: QueryExt<N>, const N: usize> From<Vec<T>> for InsertManyRows<'a, T, N> {
            fn from(vec: Vec<T>) -> Self {
                InsertManyRows::OwnedVec(vec)
            }
        }

        /// Extension trait to enable .insert_many() on Vec and slices
        pub trait BatchInsertExt<'a, T: QueryExt<N>, const N: usize> {
            fn insert_many(self) -> InsertManyQuery<'a, T, N>;
        }

        // For owned Vec - takes ownership
        impl<T: QueryExt<N>, const N: usize> BatchInsertExt<'static, T, N> for Vec<T> {
            fn insert_many(self) -> InsertManyQuery<'static, T, N> {
                InsertManyQuery::new(InsertManyRows::OwnedVec(self))
            }
        }

        // For slices - borrows data
        impl<'a, T: QueryExt<N>, const N: usize> BatchInsertExt<'a, T, N> for &'a [T] {
            fn insert_many(self) -> InsertManyQuery<'a, T, N> {
                InsertManyQuery::new(InsertManyRows::Slice(self))
            }
        }
    }
}

/// Generate query builder structs and implementations
fn gen_query_builders() -> TokenStream {
    quote! {
        /// Builder for batch INSERT statements with ON CONFLICT support
        pub struct InsertManyQuery<'a, T: QueryExt<N>, const N: usize> {
            rows: InsertManyRows<'a, T, N>,
            excluded_cols: Option<&'a [&'a str]>,
            on_conflict: Option<ConflictClause<'a>>,
        }

        enum ConflictClause<'a> {
            DoNothing {
                conflict_cols: &'a [&'a str],
            },
            DoUpdate {
                conflict_cols: &'a [&'a str],
                update_cols: &'a [&'a str],
            },
        }

        impl<'a, T: QueryExt<N>, const N: usize> InsertManyQuery<'a, T, N> {
            pub fn new(rows: InsertManyRows<'a, T, N>) -> Self {
                Self {
                    rows,
                    excluded_cols: None,
                    on_conflict: None,
                }
            }

            /// Exclude columns from the INSERT (e.g., auto-generated columns)
            ///
            /// # Example
            /// ```rust
            /// use places_col::*;
            /// rows.insert_many()
            ///     .excluding_cols(&[ID, CREATED_AT_MS, UPDATED_AT_MS])
            ///     .exec(&client)
            ///     .await?;
            /// ```
            pub fn excluding_cols(mut self, cols: &'a [&'a str]) -> Self {
                self.excluded_cols = Some(cols);
                self
            }

            /// Add ON CONFLICT DO NOTHING clause
            ///
            /// # Example
            /// ```rust
            /// use places_col::*;
            /// rows.insert_many()
            ///     .on_conflict_do_nothing(&[GOOGLE_ID])
            ///     .exec(&client)
            ///     .await?;
            /// ```
            pub fn on_conflict_do_nothing(mut self, conflict_cols: &'a [&'a str]) -> Self {
                self.on_conflict = Some(ConflictClause::DoNothing {
                    conflict_cols
                });
                self
            }

            /// Add ON CONFLICT DO UPDATE clause
            ///
            /// # Example
            /// ```rust
            /// use places_col::*;
            /// rows.insert_many()
            ///     .excluding_cols(&[ID, CREATED_AT_MS])
            ///     .on_conflict_do_update(
            ///         &[GOOGLE_ID],  // conflict columns (unique constraint)
            ///         &[DISPLAY_NAME, RATING, UPDATED_AT_MS],  // columns to update
            ///     )
            ///     .query(&client)  // Returns Vec<PlacesRow> with updated data
            ///     .await?;
            /// ```
            pub fn on_conflict_do_update(
                mut self,
                conflict_cols: &'a [&'a str],
                update_cols: &'a [&'a str],
            ) -> Self {
                self.on_conflict = Some(ConflictClause::DoUpdate {
                    conflict_cols,
                    update_cols,
                });
                self
            }

            /// Execute the INSERT statement and return the number of rows affected
            ///
            /// # Example
            /// ```rust
            /// use places_col::*;
            /// let count = rows.insert_many()
            ///     .excluding_cols(&[ID])
            ///     .exec(&client)
            ///     .await?;
            /// println!("Inserted {} rows", count);
            /// ```
            pub async fn exec<C: GenericClient>(&self, client: &C) -> Result<u64, Error> {
                let rows_slice = self.rows.as_slice();
                if rows_slice.is_empty() {
                    return Ok(0);
                }

                let (sql, params) = self.build_sql_and_params();
                client.execute(&sql, &params).await
            }

            /// Execute the INSERT statement and return inserted/updated rows
            ///
            /// Uses `RETURNING *` to fetch all inserted or updated data.
            ///
            /// # Example
            /// ```rust
            /// use places_col::*;
            /// let inserted = rows.insert_many()
            ///     .excluding_cols(&[ID])
            ///     .query(&client)
            ///     .await?;
            ///
            /// for place in inserted {
            ///     println!("Inserted with ID: {}", place.id);
            /// }
            /// ```
            pub async fn query<C: GenericClient>(&self, client: &C) -> Result<Vec<T>, Error> {
                let rows_slice = self.rows.as_slice();
                if rows_slice.is_empty() {
                    return Ok(Vec::new());
                }

                let (mut sql, params) = self.build_sql_and_params();
                sql.push_str(" RETURNING *");
                let rows = client.query(&sql, &params).await?;
                Ok(rows.into_iter().map(T::from_row).collect())
            }

            /// Build SQL and params in a single pass to avoid extra iteration
            fn build_sql_and_params<'b>(&'b self) -> (String, Vec<&'b (dyn ToSql + Sync)>) where 'a: 'b {
                let rows_slice = self.rows.as_slice();

                // Determine which columns to include
                let included_indices: Vec<usize> = T::COLS
                    .iter()
                    .enumerate()
                    .filter(|(_, col)| !self.excluded_cols.map_or(false, |excluded| excluded.contains(col)))
                    .map(|(i, _)| i)
                    .collect();

                let included_cols: Vec<&str> = included_indices
                    .iter()
                    .map(|&idx| T::COLS[idx])
                    .collect();

                let col_names = included_cols.join(", ");
                let num_cols = included_indices.len();
                let num_rows = rows_slice.len();

                // Pre-allocate for SQL building
                let mut sql = String::with_capacity(
                    128 + col_names.len() + (num_rows * num_cols * 4) // rough estimate
                );
                sql.push_str("INSERT INTO ");
                sql.push_str(T::TABLE_NAME);
                sql.push_str(" (");
                sql.push_str(&col_names);
                sql.push_str(") VALUES ");

                // Pre-allocate params with exact capacity
                let mut params = Vec::with_capacity(num_rows * num_cols);

                // Single-pass: build VALUES clauses and collect params simultaneously
                for (row_idx, row) in rows_slice.iter().enumerate() {
                    if row_idx > 0 {
                        sql.push_str(", ");
                    }
                    sql.push('(');

                    let row_params = row.to_params();
                    for (col_idx, &included_idx) in included_indices.iter().enumerate() {
                        if col_idx > 0 {
                            sql.push_str(", ");
                        }
                        // Calculate placeholder number
                        let param_num = row_idx * num_cols + col_idx + 1;
                        sql.push('$');
                        sql.push_str(&param_num.to_string());

                        // Add param
                        params.push(row_params[included_idx]);
                    }
                    sql.push(')');
                }

                // Add conflict clause if present
                if let Some(ref conflict) = self.on_conflict {
                    match conflict {
                        ConflictClause::DoNothing { conflict_cols } => {
                            sql.push_str(" ON CONFLICT (");
                            sql.push_str(&conflict_cols.join(", "));
                            sql.push_str(") DO NOTHING");
                        }
                        ConflictClause::DoUpdate {
                            conflict_cols,
                            update_cols,
                        } => {
                            sql.push_str(" ON CONFLICT (");
                            sql.push_str(&conflict_cols.join(", "));
                            sql.push_str(") DO UPDATE SET ");

                            for (i, col) in update_cols.iter().enumerate() {
                                if i > 0 {
                                    sql.push_str(", ");
                                }
                                sql.push_str(col);
                                sql.push_str(" = EXCLUDED.");
                                sql.push_str(col);
                            }
                        }
                    }
                }

                (sql, params)
            }
        }

        /// Builder for UPDATE statements
        pub struct UpdateColsQuery<'a, T: QueryExt<N>, const N: usize> {
            row: &'a T,
            cols: &'a [&'a str],
            where_cols: Option<&'a [&'a str]>,
        }

        impl<'a, T: QueryExt<N>, const N: usize> UpdateColsQuery<'a, T, N> {
            pub fn new(row: &'a T, cols: &'a [&'a str]) -> Self {
                Self {
                    row,
                    cols,
                    where_cols: None,
                }
            }

            /// Add WHERE clause columns
            ///
            /// # Example
            /// ```rust
            /// use places_col::*;
            /// place
            ///     .update_cols(&[RATING, USER_RATING_COUNT])
            ///     .where_cols(&[GOOGLE_ID])
            ///     .exec(&client)
            ///     .await?;
            /// ```
            pub fn where_cols(mut self, cols: &'a [&'a str]) -> Self {
                self.where_cols = Some(cols);
                self
            }

            /// Execute the UPDATE statement and return the number of rows affected
            ///
            /// # Example
            /// ```rust
            /// use places_col::*;
            /// let count = place
            ///     .update_cols(&[RATING])
            ///     .where_cols(&[ID])
            ///     .exec(&client)
            ///     .await?;
            /// ```
            pub async fn exec<C: GenericClient>(&self, client: &C) -> Result<u64, Error> {
                let sql = self.build_sql();
                let params = self.build_params();
                client.execute(&sql, &params).await
            }

            fn build_sql(&self) -> String {
                let set_clauses: Vec<String> = self
                    .cols
                    .iter()
                    .enumerate()
                    .map(|(i, col)| format!("{} = ${}", col, i + 1))
                    .collect();

                let mut sql = format!(
                    "UPDATE {} SET {}",
                    T::TABLE_NAME,
                    set_clauses.join(", ")
                );

                if let Some(where_cols) = self.where_cols {
                    let where_clauses: Vec<String> = where_cols
                        .iter()
                        .enumerate()
                        .map(|(i, col)| format!("{} = ${}", col, self.cols.len() + i + 1))
                        .collect();
                    sql.push_str(&format!(" WHERE {}", where_clauses.join(" AND ")));
                }

                sql
            }

            fn build_params(&self) -> Vec<&'a (dyn ToSql + Sync)> {
                let row_params = self.row.to_params();
                let mut params = Vec::new();

                // Add SET clause params
                for col in self.cols {
                    if let Some(idx) = T::COLS.iter().position(|c| c == col) {
                        params.push(row_params[idx]);
                    }
                }

                // Add WHERE clause params
                if let Some(where_cols) = self.where_cols {
                    for col in where_cols {
                        if let Some(idx) = T::COLS.iter().position(|c| c == col) {
                            params.push(row_params[idx]);
                        }
                    }
                }

                params
            }
        }
    }
}

/// Generate column constants module for a table
fn gen_column_enum(table: &TableSchema, _config: &Config) -> TokenStream {
    let table_name_snake = table.name.to_snake_case();
    let mod_name = format_ident!("{}_col", table_name_snake);

    let const_defs: Vec<TokenStream> = table
        .columns
        .iter()
        .map(|col| {
            let const_name = format_ident!("{}", col.name.to_snake_case().to_uppercase());
            let col_name = &col.name;
            let doc = format!(" Column name for `{}`", col.name);
            quote! {
                #[doc = #doc]
                pub const #const_name: &str = #col_name;
            }
        })
        .collect();

    let doc = format!(
        " Column name constants for {}.{} table",
        table.schema, table.name
    );

    quote! {
        #[doc = #doc]
        pub mod #mod_name {
            #(#const_defs)*
        }
    }
}

/// Generate QueryExt implementation for a single table
fn gen_query_ext_impl(
    table: &TableSchema,
    _type_mappings: &HashMap<String, String>,
    config: &Config,
) -> TokenStream {
    let table_name_camel = table.name.to_upper_camel_case();
    let struct_name = format_ident!("{}{}", table_name_camel, config.tables.table_struct_suffix);

    let field_count = table.columns.len();
    let full_table_name = format!("{}.{}", table.schema, table.name);

    // Generate COLS array
    let col_names: Vec<String> = table.columns.iter().map(|col| col.name.clone()).collect();

    // Generate to_params method
    let param_refs: Vec<TokenStream> = table
        .columns
        .iter()
        .map(|col| {
            let field_name = format_ident!("{}", col.name.to_snake_case());
            quote! { &self.#field_name }
        })
        .collect();

    // Generate from_row method
    let field_extractions: Vec<TokenStream> = table
        .columns
        .iter()
        .enumerate()
        .map(|(idx, col)| {
            let field_name = format_ident!("{}", col.name.to_snake_case());
            let index = proc_macro2::Literal::usize_unsuffixed(idx);
            quote! {
                #field_name: row.get(#index)
            }
        })
        .collect();

    quote! {
        impl QueryExt<#field_count> for #struct_name {
            const COLS: [&'static str; #field_count] = [
                #(#col_names),*
            ];

            const TABLE_NAME: &'static str = #full_table_name;

            fn to_params(&self) -> [&(dyn ToSql + Sync); #field_count] {
                [#(#param_refs),*]
            }

            fn from_row(row: Row) -> Self {
                Self {
                    #(#field_extractions),*
                }
            }
        }
    }
}
