//! Code generation for complete table struct definitions
//!
//! Generates Rust structs that represent complete database tables with all columns,
//! derived from database schema introspection (not just query result types).

use crate::config::Config;
use crate::schema_introspection::{map_postgres_type_to_rust, TableSchema};
use heck::{ToSnakeCase, ToUpperCamelCase};
use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use std::collections::HashMap;

/// Generate a complete tables module with all table struct definitions
///
/// # Arguments
/// * `tables` - Introspected table schemas from the database
/// * `config` - Configuration including type mappings
///
/// # Returns
/// TokenStream containing all table struct definitions
pub fn gen_tables_module(tables: &[TableSchema], config: &Config) -> TokenStream {
    // Build type mappings from config
    let type_mappings: HashMap<String, String> = config
        .types
        .mapping
        .iter()
        .map(|(k, v)| {
            let rust_type = match v {
                crate::config::TypeMapping::Simple(s) => s.clone(),
                crate::config::TypeMapping::Detailed { rust_type, .. } => rust_type.clone(),
            };
            (k.clone(), rust_type)
        })
        .collect();

    let struct_defs: Vec<TokenStream> = tables
        .iter()
        .map(|table| gen_table_struct(table, &type_mappings, config))
        .collect();

    quote! {
        //! Auto-generated complete table struct definitions
        //! DO NOT EDIT - Regenerated by Clorinde from database schema introspection
        //!
        //! These structs represent complete database tables with all columns,
        //! suitable for batch operations via the QueryExt trait.

        use tokio_postgres::types::{ToSql, FromSql};

        #(#struct_defs)*
    }
}

/// Generate a single table struct definition
fn gen_table_struct(
    table: &TableSchema,
    type_mappings: &HashMap<String, String>,
    config: &Config,
) -> TokenStream {
    let table_name_camel = table.name.to_upper_camel_case();
    let struct_name = format_ident!(
        "{}{}",
        table_name_camel,
        config.tables.table_struct_suffix
    );

    let fields: Vec<TokenStream> = table
        .columns
        .iter()
        .map(|col| {
            let field_name = format_ident!("{}", col.name.to_snake_case());
            let rust_type_str = map_postgres_type_to_rust(col, type_mappings);
            let rust_type: syn::Type = syn::parse_str(&rust_type_str)
                .unwrap_or_else(|_| syn::parse_str("String").unwrap());

            quote! {
                pub #field_name: #rust_type
            }
        })
        .collect();

    let doc_comment = format!(
        " Complete table struct for '{}.{}' ({} columns)",
        table.schema,
        table.name,
        table.columns.len()
    );

    // Generate derive traits
    let derive_traits = if config.serialize {
        quote! { #[derive(Debug, Clone, serde::Serialize)] }
    } else {
        quote! { #[derive(Debug, Clone)] }
    };

    quote! {
        #[doc = #doc_comment]
        #derive_traits
        pub struct #struct_name {
            #(#fields),*
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schema_introspection::ColumnDef;

    #[test]
    fn test_gen_table_struct() {
        let table = TableSchema {
            name: "restaurants".to_string(),
            schema: "public".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".to_string(),
                    data_type: "bigint".to_string(),
                    udt_name: "int8".to_string(),
                    is_nullable: false,
                    column_default: Some("nextval('restaurants_id_seq')".to_string()),
                    ordinal_position: 1,
                },
                ColumnDef {
                    name: "google_id".to_string(),
                    data_type: "text".to_string(),
                    udt_name: "text".to_string(),
                    is_nullable: false,
                    column_default: None,
                    ordinal_position: 2,
                },
                ColumnDef {
                    name: "rating".to_string(),
                    data_type: "double precision".to_string(),
                    udt_name: "float8".to_string(),
                    is_nullable: true,
                    column_default: None,
                    ordinal_position: 3,
                },
            ],
            primary_keys: vec!["id".to_string()],
        };

        let type_mappings = HashMap::new();
        let mut config = Config::default();
        config.serialize = true;
        config.tables.table_struct_suffix = "Table".to_string();

        let tokens = gen_table_struct(&table, &type_mappings, &config);
        let code = tokens.to_string();

        assert!(code.contains("pub struct RestaurantTable"));
        assert!(code.contains("pub id: i64"));
        assert!(code.contains("pub google_id: String"));
        assert!(code.contains("pub rating: Option < f64 >"));
        assert!(code.contains("serde :: Serialize"));
    }
}
