//! Code generation for complete table struct definitions
//!
//! Generates Rust structs that represent complete database tables with all columns,
//! derived from database schema introspection (not just query result types).

use crate::config::Config;
use crate::schema_introspection::{TableSchema, map_postgres_type_to_rust};
use heck::{ToSnakeCase, ToUpperCamelCase};
use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use std::collections::HashMap;

/// Generate a complete tables module with all table struct definitions
///
/// # Arguments
/// * `tables` - Introspected table schemas from the database
/// * `config` - Configuration including type mappings
///
/// # Returns
/// TokenStream containing all table struct definitions
pub fn gen_tables_module(tables: &[TableSchema], config: &Config) -> TokenStream {
    // Build type mappings from config
    let type_mappings: HashMap<String, String> = config
        .types
        .mapping
        .iter()
        .map(|(k, v)| {
            let rust_type = match v {
                crate::config::TypeMapping::Simple(s) => s.clone(),
                crate::config::TypeMapping::Detailed { rust_type, .. } => rust_type.clone(),
            };
            (k.clone(), rust_type)
        })
        .collect();

    let struct_defs: Vec<TokenStream> = tables
        .iter()
        .map(|table| gen_table_struct(table, &type_mappings, config))
        .collect();

    quote! {
        //! Auto-generated complete table struct definitions
        //! DO NOT EDIT - Regenerated by Clorinde from database schema introspection
        //!
        //! These structs represent complete database tables with all columns,
        //! suitable for batch operations via the QueryExt trait.

        use tokio_postgres::types::{ToSql, FromSql};

        #(#struct_defs)*
    }
}

/// Generate a single table struct definition
fn gen_table_struct(
    table: &TableSchema,
    type_mappings: &HashMap<String, String>,
    config: &Config,
) -> TokenStream {
    let table_name_camel = table.name.to_upper_camel_case();
    let struct_name = format_ident!("{}{}", table_name_camel, config.tables.table_struct_suffix);
    let borrowed_struct_name = format_ident!(
        "{}{}Borrowed",
        table_name_camel,
        config.tables.table_struct_suffix
    );

    let fields: Vec<TokenStream> = table
        .columns
        .iter()
        .map(|col| {
            let field_name = format_ident!("{}", col.name.to_snake_case());
            let rust_type_str = map_postgres_type_to_rust(col, type_mappings);
            let rust_type: syn::Type = syn::parse_str(&rust_type_str)
                .unwrap_or_else(|_| syn::parse_str("String").unwrap());

            quote! {
                pub #field_name: #rust_type
            }
        })
        .collect();

    // Generate borrowed fields (convert String to &'a str, Vec<T> to &'a [T], etc.)
    let borrowed_fields: Vec<TokenStream> = table
        .columns
        .iter()
        .map(|col| {
            let field_name = format_ident!("{}", col.name.to_snake_case());
            let rust_type_str = map_postgres_type_to_rust(col, type_mappings);
            let borrowed_type_str = convert_to_borrowed_type(&rust_type_str);
            let borrowed_type: syn::Type = syn::parse_str(&borrowed_type_str)
                .unwrap_or_else(|_| syn::parse_str("&'a str").unwrap());

            quote! {
                pub #field_name: #borrowed_type
            }
        })
        .collect();

    // Generate From<Borrowed> for Owned implementation
    let field_conversions: Vec<TokenStream> = table
        .columns
        .iter()
        .map(|col| {
            let field_name = format_ident!("{}", col.name.to_snake_case());
            let rust_type_str = map_postgres_type_to_rust(col, type_mappings);

            // Generate appropriate conversion based on type
            if rust_type_str == "String" {
                quote! { #field_name: value.#field_name.to_owned() }
            } else if rust_type_str.starts_with("Vec<") {
                // Arrays stay owned in borrowed variant, just move them
                quote! { #field_name: value.#field_name }
            } else if rust_type_str.starts_with("Option<String>") {
                quote! { #field_name: value.#field_name.map(|s| s.to_owned()) }
            } else if rust_type_str.starts_with("Option<Vec<") {
                // Optional arrays stay owned in borrowed variant, just move them
                quote! { #field_name: value.#field_name }
            } else {
                // For Copy types (i32, i64, f64, bool, etc.) and other types, just copy
                quote! { #field_name: value.#field_name }
            }
        })
        .collect();

    let doc_comment = format!(
        " Complete table struct for '{}.{}' ({} columns)",
        table.schema,
        table.name,
        table.columns.len()
    );

    let borrowed_doc_comment = format!(
        " Borrowed variant of {} for zero-copy deserialization",
        struct_name
    );

    // Generate derive traits
    let derive_traits = if config.serialize {
        quote! { #[derive(Debug, Clone, serde::Serialize)] }
    } else {
        quote! { #[derive(Debug, Clone)] }
    };

    // Borrowed structs can't derive Serialize without explicit lifetime handling
    let borrowed_derive_traits = quote! { #[derive(Debug, Clone)] };

    // Check if any field actually uses the 'a lifetime (String -> &'a str, Option<String> -> Option<&'a str>)
    let has_borrowed_fields = table.columns.iter().any(|col| {
        let rust_type = map_postgres_type_to_rust(col, type_mappings);
        rust_type == "String" || rust_type == "Option<String>"
    });

    // Check if all fields are Copy types
    let all_copy_fields = table.columns.iter().all(|col| {
        let rust_type = map_postgres_type_to_rust(col, type_mappings);
        !rust_type.contains("String") && !rust_type.contains("Vec<") && !rust_type.contains("json")
    });

    if all_copy_fields {
        // For all-Copy tables, generate Copy struct only (no borrowed variant needed)
        quote! {
            #[doc = #doc_comment]
            #[derive(Debug, Clone, Copy)]
            pub struct #struct_name {
                #(#fields),*
            }
        }
    } else if has_borrowed_fields {
        // Generate borrowed struct WITH lifetime parameter (has actual String fields to borrow)
        quote! {
            #[doc = #doc_comment]
            #derive_traits
            pub struct #struct_name {
                #(#fields),*
            }

            #[doc = #borrowed_doc_comment]
            #borrowed_derive_traits
            pub struct #borrowed_struct_name<'a> {
                #(#borrowed_fields),*
            }

            impl<'a> From<#borrowed_struct_name<'a>> for #struct_name {
                fn from(value: #borrowed_struct_name<'a>) -> Self {
                    Self {
                        #(#field_conversions),*
                    }
                }
            }
        }
    } else {
        // Generate borrowed struct WITHOUT lifetime parameter (has Vec/Json but no String fields)
        // Still need borrowed variant for query code compatibility, but no lifetime needed
        quote! {
            #[doc = #doc_comment]
            #derive_traits
            pub struct #struct_name {
                #(#fields),*
            }

            #[doc = #borrowed_doc_comment]
            #borrowed_derive_traits
            pub struct #borrowed_struct_name {
                #(#borrowed_fields),*
            }

            impl From<#borrowed_struct_name> for #struct_name {
                fn from(value: #borrowed_struct_name) -> Self {
                    Self {
                        #(#field_conversions),*
                    }
                }
            }
        }
    }
}

/// Convert an owned Rust type to its borrowed equivalent
fn convert_to_borrowed_type(rust_type: &str) -> String {
    if rust_type == "String" {
        "&'a str".to_string()
    } else if let Some(_inner) = rust_type
        .strip_prefix("Vec<")
        .and_then(|s| s.strip_suffix(">"))
    {
        // Arrays cannot be borrowed from postgres - keep as Vec<T>
        rust_type.to_string()
    } else if let Some(inner) = rust_type.strip_prefix("Option<String") {
        if inner == ">" {
            "Option<&'a str>".to_string()
        } else {
            rust_type.to_string() // Fallback for malformed types
        }
    } else if rust_type.starts_with("Option<Vec<") {
        // Optional arrays also cannot be borrowed - keep as Option<Vec<T>>
        rust_type.to_string()
    } else {
        // For Copy types and other types, keep as-is
        rust_type.to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schema_introspection::ColumnDef;

    #[test]
    fn test_gen_table_struct() {
        let table = TableSchema {
            name: "places".to_string(),
            schema: "public".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".to_string(),
                    data_type: "bigint".to_string(),
                    udt_name: "int8".to_string(),
                    is_nullable: false,
                    column_default: Some("nextval('places_id_seq')".to_string()),
                    ordinal_position: 1,
                    is_identity: false,
                },
                ColumnDef {
                    name: "google_id".to_string(),
                    data_type: "text".to_string(),
                    udt_name: "text".to_string(),
                    is_nullable: false,
                    column_default: None,
                    ordinal_position: 2,
                    is_identity: false,
                },
                ColumnDef {
                    name: "rating".to_string(),
                    data_type: "double precision".to_string(),
                    udt_name: "float8".to_string(),
                    is_nullable: true,
                    column_default: None,
                    ordinal_position: 3,
                    is_identity: false,
                },
            ],
            primary_keys: vec!["id".to_string()],
        };

        let type_mappings = HashMap::new();
        let mut config = Config::default();
        config.serialize = true;
        config.tables.table_struct_suffix = "Table".to_string();

        let tokens = gen_table_struct(&table, &type_mappings, &config);
        let code = tokens.to_string();

        assert!(code.contains("pub struct PlacesTable"));
        assert!(code.contains("pub id : i64"));
        assert!(code.contains("pub google_id : String"));
        assert!(code.contains("pub rating : Option < f64 >"));
        assert!(code.contains("serde :: Serialize"));
    }
}
